Logistic Growth Function and Tests
arfc/pygenesys pull request #16
Opened 2021-07-22 21:04 UTC by nsryan2

This PR adds the capability for a logistic growth model and closes #11. 
I based this off of the website in the issue and the [wikipedia page](https://en.wikipedia.org/wiki/Logistic_function).

2021-07-22 21:04 UTC, pep8speaks commented
Hello @nsryan2! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`pygenesys/tests/utils_tests/test_growth_model.py`](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py):

> [Line 5:1](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py#L5): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 10:80](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py#L10): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 26:80](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py#L26): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 44:80](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py#L44): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 65:80](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py#L65): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (96 > 79 characters)
> [Line 67:80](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py#L67): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 69:11](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/tests/utils_tests/test_growth_model.py#L69): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`pygenesys/utils/growth_model.py`](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/utils/growth_model.py):

> [Line 136:23](https://github.com/arfc/pygenesys/blob/ebcfe3a62b45468b68a53b0c3a303f1313f1ff1f/pygenesys/utils/growth_model.py#L136): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-07-22 22:05 UTC, samgdotson requested changes
Thanks for making this PR! It looks good. I've requested some minor changes and ask that you find another more "pythonic" way to calculate the values for logistic growth (rather than a for-loop). 

Finally, don't forget to update the documentation! If it says "TODO: add logistic" and you've done it, ditch that comment!

I'll merge once these changes are made. You can use the "add suggestion to batch" button to reduce the number of emails you send with each change.

2021-07-22 22:05 UTC, samgdotson commented on pygenesys/tests/utils_tests/test_growth_model.py
> +    growth = pyutgm.exponential_growth(init_value,
```suggestion
    growth = growth_model.exponential_growth(init_value,
```

2021-07-22 22:05 UTC, samgdotson commented on pygenesys/tests/utils_tests/test_growth_model.py
> +    growth = pyutgm.logistic_growth(init_value,
```suggestion
    growth = growth_model.logistic_growth(init_value,
```

2021-07-22 22:07 UTC, samgdotson commented on pygenesys/utils/growth_model.py
> +    np.asarray(growth_data)
Also, if you don't introduce ``growth_data`` as a list, there is no reason to convert it to an array. The function will be applied to ``years`` which is already an ``np.array``.

2021-07-23 15:00 UTC, nsryan2 commented on pygenesys/utils/growth_model.py
> +    np.asarray(growth_data)
Sure thing, I can switch it to a lambda function! Something that gave me pause with that is the fifth bullet point in the programming recommendations section of the [PEP8 style guide](https://www.python.org/dev/peps/pep-0008/#programming-recommendations), but they look much nicer as lambda functions

2021-07-23 15:35 UTC, nsryan2 commented
@samgdotson Should be all good to go! Thanks for the feedback

2025-02-11 17:43 UTC, merged